language: elixir

elixir:
    - 1.6
    - 1.5

otp_release:
    - 20.1
    - 19.3

env:
  - MIX_ENV=test

stages:
  - test

script:
  - mix deps.get
  - mix deps.compile
  - mix compile
  - elixirc -o spec/lib spec/lib
  - mix coveralls.travis
