language: elixir

elixir:
    - 1.6
    - 1.5

otp_release:
    - 20.1
    - 19.3

env:
  - MIX_ENV=test

stages:
  - test
  - name: deploy
    if: tag =~ ^v1

script:
  - mix deps.get
  - mix deps.compile
  - mix compile
  - elixirc -o spec/lib spec/lib
  - mix coveralls.travis

jobs:
  include:
    - stage: deploy
      provider: script
      script: mix coveralls
      after_script:
        - mix hex.config username $HEX_USERNAME
        - mix hex.config key $HEX_KEY
        - mix hex.publish
      on:
        tags: true
