language: elixir

elixir:
  - 1.5
  - 1.6

otp_release:
  - 19.3
  - 20.1

env:
  - MIX_ENV=test

script: mix coveralls.travis

deploy:
  provider: script
  script: mix coveralls
  after_script:
    - mix hex.config username $HEX_USERNAME
    - mix hex.config key $HEX_KEY
    - mix hex.publish
  on:
    tags: true
